# SPDX-License-Identifier: BSD-3-Clause
# Minicosmos
# (C) 2021 China First Softwere Factory, All rights reserved.

# Main Makefile of i386

include debug/debug.mk

everything:
	make -C boot everything

clean:
	make -C boot clean

cleanall:
	make -C boot cleanall

try: debug_try

d_try: debug_d_try


